#!/usr/bin/php
<?php
if ($argc == 2) {
    if (!is_numeric($argv[1])) {
	echo 'vous devez rentrer un age';
	return;
    }
    if ($argv[1] < 18) {
        echo 'Vous êtes mineur(e)';
    } else {
        echo 'vous êtes majeur(e)';
    }
} else {
    echo 'Les arguments ne correspondent pas';
}
?>
